modLoader = "javafml"
loaderVersion = "[41,)" 

author = "${author}"
license = "Copyright (c) ${vendor}"
issueTrackerURL = "https://github.com/fubira/HorseInfoReloaded/issues"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
displayURL="https://github.com/fubira/HorseInfoReloaded/"
credits="${vendor}"
author = "${author}"

description='''
HorseInfoReloaded is display mod for ability of Horses.
inspired by HorseInfo/(by TTTA2)
'''

[[dependencies.horseinforeloaded]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.horseinforeloaded]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

