plugins {
    id("net.fabricmc.fabric-loom") version("${loom_version}")
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

def resourceProperties = new HashMap<String, Object>(project.properties)

dependencies {
    minecraft(libs.minecraft)

    implementation(libs.bundles.fabric)
    implementation(libs.clothConfigFabric)

    implementation(project(":common"))
}

tasks {
    processResources {
        duplicatesStrategy = DuplicatesStrategy.INCLUDE

        from("src/main/resources", "../common/src/main/resources")

        filesMatching("fabric.mod.json") {
            expand(resourceProperties)
        }
    }

    compileJava {
        options.encoding = "UTF-8"
        options.release.set(25)
    }
}

loom {
    runs {
        create("horseInfoClient") {
            client()

            property("fabric.log.level", "debug")
            vmArg("-XX:+ShowCodeDetailsInExceptionMessages")
        }
        create("horseInfoServer") {
            server()

            property("fabric.log.level", "debug")
            vmArg("-XX:+ShowCodeDetailsInExceptionMessages")
        }
    }
}
