modLoader="javafml"
loaderVersion="[31,)" 

author="fubira"
issueTrackerURL="https://github.com/fubira/HorseInfoReloaded/issues"

[[mods]]
modId="horseinfo"
version="${file.jarVersion}"
displayName="HorseInfoReloaded"
displayURL="https://github.com/fubira/HorseInfoReloaded/"
credits="fubira/KenmoMinecraftClub"
author="fubira"

description='''
HorseInfoReloaded is display mod for ability of Horses.
inspired by HorseInfo/(by TTTA2)
'''

[[dependencies.horseinfo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.horseinfo]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

