[plugins]
fabric-loom = "net.fabricmc.fabric-loom:1.16.2"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version = "26.1.2" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version = "0.19.2" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version = "0.149.1+26.1.2" }
neoforge = { group = "net.neoforged", name = "neoforge", version = "26.1.2.65-beta" }
clothConfigFabric = { group = "me.shedaniel.cloth", name = "cloth-config-fabric", version = "26.1.154" }
clothConfigNeoForge = { group = "me.shedaniel.cloth", name = "cloth-config-neoforge", version = "26.1.154" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.10.1" }
log4japi = { group = "org.apache.logging.log4j", name = "log4j-api", version = "2.22.1" }
log4jcore = { group = "org.apache.logging.log4j", name = "log4j-core", version = "2.22.1" }

[bundles]
fabric = ["fabric-loader", "fabric-api"]
