modLoader = "${modloader}"
loaderVersion = "${modloader_version_range}"

author = "${mod_authors}"
license = "${mod_license}, Copyright (c) ${mod_vendor}"
issueTrackerURL = "https://github.com/fubira/HorseInfoReloaded/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL="https://github.com/fubira/HorseInfoReloaded/"
credits="${mod_vendor}"
author = "${mod_authors}"

description='''
HorseInfoReloaded is display mod for ability of Horses.
inspired by HorseInfo/(by TTTA2)
'''

[[dependencies.horseinforeloaded]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.horseinforeloaded]]
    modId="neoforge"
    mandatory=true
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"

